### ISSUE TITLE
smile.amazon.com

### ISSUE THREAD

**Issue by jawz101** [bhadaway/canonical#1]
Can it keep the prefix for Amazon Smile pages?  See the reviews on your add-on page to see why.

People use the Amazon Smile program to donate to charities.

**Comment by bhadaway** [comment]
Hey jawz101,

Note that this add-on doesn't redirect or change the current page's URL in any way _automatically_.

It merely offers the option to redirect yourself to the canonical version of the URL, if one has been suggested by the page, which is set by the website's webmaster and is something that isn't controlled by the add-on.

I tested https://smile.amazon.com/ and it doesn't appear that this site even offers a canonical link for its pages.

It sounds like what's happening might be unrelated to the Canonical add-on. Either way, I'd be happy to keep helping you troubleshoot what's going on if you can provide me with more specific steps to recreate the problem.

Thanks

**Comment by bhadaway** [comment]
Thanks. Good to know. :)
