### ISSUE TITLE
Copy canonical to clipboard

### ISSUE THREAD

**Issue by Cimbali** [bhadaway/canonical#4]
Would it be possible to add a feature to copy the canonical link of the page to the clipboard?

I found myself on a nasty website where I could click the canonical link but it would then redirect me to a page with added parameters − however I want to save the canonical URLs, so I had to 1) click the canonical icon to get rid of most of the garbage, 2) select which part of the address bar to copy/paste, 3) ctrl + c.

I think this feature would be useful if you’re already on a non-canonical page, but if you want to save or share it for whatever reason, and want to use the canonical link for that.

I think this could be pretty easy to implement:
- just requires adding the `clipboardWrite` permission I believe
- either with shift + click on the icon, or with an (optional) keyboard shortcut
- then a function that simply does [`Clipboard.writeText()`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText), e.g.: `navigator.clipboard.writeText(canonicalUrl)`

**Comment by bhadaway** [comment]
That's just a one-way permission, right? To add something to the clipboard, but we wouldn't have to grant the add-on access to what's already in someone's clipboard? Privacy/security is always a concern for me, and keeping things simple is the best policy where that's concerned.

What about adding "Copy" to the icon context menu when right-clicking on it? Or perhaps that's a reserved space for official Firefox options only?

**Comment by Cimbali** [comment]
Yes it’s a separate permission from `clipboardRead`. I don’t know if you can add options to a pageAction context menu, but I don’t think so. The [pageAction listener doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction/onClicked) says:

> Note that the right-click is not supported because Firefox consumes that click to display the context menu before this event is triggered.

**Comment by bhadaway** [comment]
If you want to try submitting this idea as a pull request, I'll be happy to review and consider it.

**Comment by bhadaway** [comment]
Done: https://addons.mozilla.org/firefox/addon/canonical-link/

Thanks again for your help. :)
