### ISSUE TITLE
False positive on D&D Beyond

### ISSUE THREAD

**Issue by DarwinAwardWinner** [bhadaway/canonical#5]
In D&D Beyond, character sheet URLs have the form `https://www.dndbeyond.com/characters/XXXXXXX` where the X's are 7 numeric digits. Canonical not-so-helpfully offers a link to `https://www.dndbeyond.com/characters`, which is the list of character sheets.

**Comment by bhadaway** [comment]
I'm not able to find a link to any of the character pages on https://www.dndbeyond.com/characters, if you wouldn't mind sharing with me a live example?

**Comment by DarwinAwardWinner** [comment]
Try this link to my character sheet, I think the link should be public (works in a private tab): https://www.dndbeyond.com/characters/4717594

**Comment by bhadaway** [comment]
Digging a little deeper, I can see that this site isn't even powered by WordPress. It's not my plugin (https://wordpress.org/plugins/canonical-link/) that's creating the canonical link:

`<link rel="canonical" href="/characters" />`

If you're not here for WordPress support, and you're referring to my browser add-on (https://addons.mozilla.org/addon/canonical-link/), please note that my add-on has no effect on the canonical links of pages. That would be impossible; it merely reflects the URL declared in the code.

It looks like this site is a custom build, and isn't using any kind of CMS. Still, if it's partly built with PHP, I can probably help. I'm guessing this issue isn't relevant to me and I can't though, so closing for now. I'm not sure if you're an admin on that website or just a user, but you may want to contact their support if you feel they're implementing canonicalization incorrectly.

**Comment by DarwinAwardWinner** [comment]
Oh, yes, sorry for the confusion. I'm here for the browser add-on. I understand now, for some reason the site declares that "/characters" is the canonical link, and the add-on just surfaces that information. I have no idea why they would do that. (I'm just a user, I doubt I could get them to change it.) Thank you for looking into it.

**Comment by bhadaway** [comment]
You're welcome.
