### ISSUE TITLE
Validate canonical URL before showing icon

### ISSUE THREAD

**Issue by Cimbali** [bhadaway/canonical#8]
I just was on a website where the canonical icon showed in the address bar, but the URL just said `https://`. When I looked in the page source I could see the add-on did nothing wrong, as the page contained:

```html
<link href="https://" rel="canonical"/>
```

I think it would be a good idea to validate the URL is valid, before displaying the icon, e.g. `try { new URL(url); } catch (err) { /* not valid */ } ; `

**Comment by bhadaway** [comment]
Nay on this one. This actually came up before I believe. My conclusion was that it should display whatever is there no matter what, even when erroneous, so that site users or the webmaster themselves could easily discover and fix such issues.
